[package]
name = "boids"
version = "0.4.2"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boids-core = { path = "../.." }
pollster = "0.3.0"
tracing-subscriber = "0.3.17"
